---
- name: install homebrew taps
  homebrew_tap:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew_taps }}"

- name: upgrade homebrew cask packages
  homebrew_cask:
    name: "{{ item }}"
    state: upgraded
    update_homebrew: yes
    upgrade_all: yes
  with_items: "{{ homebrew_cask_packages }}"

- name: install homebrew cask packages
  homebrew_cask:
    name: "{{ item }}"
    state: present
    update_homebrew: yes
  with_items: "{{ homebrew_cask_packages }}"

- name: install homebrew packages
  homebrew:
    name: "{{ homebrew_packages }}"
    state: present
    update_homebrew: yes

- find:
    paths: /usr/local
    file_type: any
  register: localdir

- name: fix group permissions /usr/local
  file:
    path: "{{ item.path }}"
    group: brew
    mode: g+w
    recurse: true
  with_items: "{{ localdir.files }}"
  become: true

- name: fix group permissions /Library/Caches/Homebrew
  file:
    path: /Library/Caches/Homebrew
    group: brew
    mode: g+w
    recurse: true
  become: true

- name: fix group permissions /opt/homebrew-cask
  file:
    path: /opt/homebrew-cask
    group: brew
    mode: g+w
    recurse: true
  become: true
